---
title: "R1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Data

```{r}
pm <- read.table("Prob_model.csv",sep=",",header=TRUE)
r <- read.table("ratio_table.csv",sep=",",header=TRUE)
```

```{r}
head(r)
head(pm)
```


## Construct $A_{x}$

```{r}
# precondition: cond=[type,lane,avgTraf,opsta,length,ass,age]


# Ax
# description: i) if initial state is 0 (ass 1-3), prob of repair (state 1) of age t = Xt, Ax = APV of repair cost for a good bridge
samp=r[1,0:7]
# print(samp)
as2=pm[pm$Road.Type==samp$type & pm$Number.of.Lanes==samp$lane & pm$Avg.Daily.Traffic==samp$avg & pm$Operational.Status==samp$status & pm$Bridge.Length==samp$length & pm$Assessment==2,]
as4=pm[pm$Road.Type==samp$type & pm$Number.of.Lanes==samp$lane & pm$Avg.Daily.Traffic==samp$avg & pm$Operational.Status==samp$status & pm$Bridge.Length==samp$length & pm$Assessment==4,]
as7=pm[pm$Road.Type==samp$type & pm$Number.of.Lanes==samp$lane & pm$Avg.Daily.Traffic==samp$avg & pm$Operational.Status==samp$status & pm$Bridge.Length==samp$length & pm$Assessment==7,]

x=samp$current_age
i=.05
v=1/(1+i)
px01=as.numeric(as2[1,(6+x):121])
px00=1-px01
px12=as.numeric(as4[1,(6+x):121])
px10=.5*(1-px12)
px11=1-px10-px12
px20=rep(1,length(px01))
value=v*px01[1]

tpx01=rep(as2[1,6+x],length(px01))
tpx00=rep(1-as2[1,6+x],length(px01))
for (t in (2:(116-x))){
  tpx00[t]=tpx01[t-1]*px10[t]+tpx00[t-1]*px00[t]
  tpx01[t]=tpx00[t-1]*px01[t]+tpx01[t-1]*px11[t]
  value=value+v^t*tpx00[t-1]*px01[t]
}

tb <- cbind(px00,px01,px10,px11,px12,px20,tpx00,tpx01)
# do.call(rbind.data.frame, Map('c', A=px00, B=px01))

print(tb)
print(value)

```

